use_frameworks!

target 'SwiftJSBridge_Example', :exclusive => true do
  pod 'SwiftJSBridge', :path => '../'
end

target 'SwiftJSBridge_Tests', :exclusive => true do
  pod 'SwiftJSBridge', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
